site_name: OPIL
site_url: https://opil-documentation.readthedocs.org
repo_url: https://github.com/opil/documentation
site_description: OPIL Documentation
site_author: OPIL Team
docs_dir: final_documentation_structure
site_dir: html

markdown_extensions:
      - toc:
              baselevel: 3
      - fenced_code
      - attr_list
      - pymdownx.arithmatex
      
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

use_directory_urls: false

theme:
      name: readthedocs
      highlightjs: true
      hljs_languages:
            - yaml
            - django
            - bash
            - yml
pages:
      - Home: index.md
      - OPIL Intro:
              - OPIL Architecture: OPIL_Intro/OPIL_Architecture.md
              - OPIL Deployment: OPIL_Intro/deployment.md
              - OPIL Server: OPIL_Intro/opil_server.md
      - Business Process Optimization (BPO): BPO/Getting_Started___Installation_Guide__User_Manual.md
      - Human Machine Interface (HMI):
              - Getting Started: HMI/Getting_Started.md
              - Installation Guide: HMI/Installation_Guide.md
              - User Manual: HMI/User_Manual.md
              - API: HMI/hmi_rest_api.md
      - Robot Agent Node VC (RAN VC):
              - RAN VC Documentation: RAN_VC/VC_RAN_documentation_v.0.6.md
      - Robot Agent Node:
              - Getting Started: RAN/Getting_Started.md
              - Installation Guide: RAN/Installation_Guide.md
              - User Manual: RAN/User_Manual.md
      - Sensor Agent Node VC (SAN VC):
              - SAN VC Documentation: SAN_VC/VC_SAN_documentation_v.0.5.md
      - Sensor Agent Node:
              - Getting Started: SAN/Getting_Started.md
              - Installation Guide: SAN/Installation_Guide.md
              - User Manual:
                      - Configuration: SAN/User_manual/Configuration.md
                      - SAN API: SAN/User_manual/SAN_API.md
                      - SAN Drivers: SAN/User_manual/SAN_Drivers.md
      - Sensing & Perception (SP):
              - Central SP Getting Started: SP/Central_SP_Getting_Started.md
              - Central SP Intallation Guide: SP/Central_SP_Installation_Guide.md
              - Central SP User Guide API: SP/Central_SP_User_Guide1_API.md
              - Central SP User Guide Interfaces: SP/Central_SP_User_Guide2_interfaces.md
              - Local SP Getting Started: SP/Local_SP_Getting_Started.md
              - Local SP Intallation Guide: SP/Local_SP_Installation_Guide.md
              - Local SP User Guide API: SP/Local_SP_User_Guide1_API.md
              - Local SP User Guide Interfaces: SP/Local_SP_User_Guide2_interfaces.md
      - Task Planner (TP):
              - Getting Started: TP/Getting_Started.md
              - Installation Guide: TP/Installation_Guide.md
              - User Manual:
                      - Configuration TP BPO: TP/User_Manual/config_tp_bpo.md
                      - How it works: TP/User_Manual/how_it_works.md
                      - Interfaces: TP/User_Manual/interfaces.md
